name: Traverse
version: '${version}'
main: mc.unraveled.reforged.plugin.Traverse
api-version: 1.19
authors: [ SimplexDevelopment ]
description: "A plugin designed for the Unraveled: Reforged server."
website: https://github.com/SimplexDevelopment/Traverse
depend: [ Vault ]
softdepend: [ EssentialsX, EssentialsXSpawn ]

